### PR TITLE
feat: Update to latest mono-wasm

### LINKED ISSUE #245: Some changes needed by Wave Engine
Hi!

We, @WaveEngine, would like moving to this package for everything Mono/Wasm related. Among other things, we are interested in statically linking the OpenGL layer to gain some speed in there.

Our mate @davilovick has pushed some changes to consume the latest Mono bits, which has required bumping Emscripten, which has required moving into WSL for some IO stuff:

https://github.com/unoplatform/Uno.Wasm.Bootstrap/compare/master...davilovick:master

Would there be any chance those could be included in your repo? We have not wanted to create a PR directly, as consider you may find a better way of doing things, or even have any other block.

We are considering as well forking this package to quickly offer such in our next release but, ideally, would really like to simply consume yours :-)

Thanks in advance!

### PR DESCRIPTION
**Pull request by jeromelaban**
Fixes #245

### CODE REVIEW

**Comment by mattleibow** [comment]
I got some build errors and warnings using this PR:

```
...
FAILED: pinvoke-table.h.tmp
...
4>  [00:00:02.8298607] The return type of pinvoke callback method 'System.Void System.Net.NetworkInformation.MacNetworkChange::HandleCallback(System.IntPtr,System.Net.NetworkInformation.MacNetworkChange/NetworkReachabilityFlags,System.IntPtr)' needs to be blittable.
```
not sure why `void` is not blittable...

I also got this warning:
```
emcc: warning: argument unused during compilation: '-lidbfs.js' [-Wunused-command-line-argument]
```

```
4>  [00:00:02.0604573] [205/212] "/home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk/emsdk" construct_env emsdk_env.sh
4>  [00:00:02.0605606] Adding directories to PATH:
4>  [00:00:02.0605720] PATH += /home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk
4>  [00:00:02.0605747] PATH += /home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk/upstream/emscripten
4>  [00:00:02.0605774] PATH += /home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk/node/12.9.1_64bit/bin
4>  [00:00:02.0605795]
4>  [00:00:02.0605814] Setting environment variables:
4>  [00:00:02.0605833] EMSDK = /home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk
4>  [00:00:02.0605878] EM_CONFIG = /home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk/.emscripten
4>  [00:00:02.0605898] EM_CACHE = /home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk/upstream/emscripten/cache
4>  [00:00:02.0605917] EMSDK_NODE = /home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk/node/12.9.1_64bit/bin/node
4>  [00:00:02.0605939]
4>  [00:00:02.8297522] [206/212] mono /mnt/c/Users/mattl/AppData/Local/Temp/mono-wasm-05a57bed403/wasm-bcl/wasm_tools/wasm-tuner.exe --gen-pinvoke-table System.Native,libSkiaSharp Uno.Wasm.TimezoneData.dll netstandard.dll mscorlib.dll System.dll Mono.Security.dll System.Xml.dll System.Numerics.dll System.Core.dll WebAssembly.Net.WebSockets.dll WebAssembly.Bindings.dll System.Memory.dll System.Data.dll System.Transactions.dll System.Data.DataSetExtensions.dll System.Drawing.Common.dll System.IO.Compression.dll System.IO.Compression.FileSystem.dll System.ComponentModel.Composition.dll System.Net.Http.dll System.Net.Http.WebAssemblyHttpHandler.dll System.Runtime.Serialization.dll System.ServiceModel.Internals.dll System.Xml.Linq.dll SkiaSharpSample.Wasm.dll Microsoft.Extensions.Logging.Abstractions.dll System.Runtime.dll System.Resources.ResourceManager.dll System.Diagnostics.Debug.dll System.Collections.Concurrent.dll System.Collections.dll System.Globalization.dll System.Linq.dll System.Reflection.dll Uno.UI.dll Uno.Xaml.dll Uno.Foundation.dll Uno.Core.dll System.Collections.Immutable.dll System.Runtime.Extensions.dll System.Threading.dll CommonServiceLocator.dll System.Reflection.Emit.Lightweight.dll System.Reflection.Emit.ILGeneration.dll Microsoft.Extensions.Logging.dll Microsoft.Extensions.DependencyInjection.Abstractions.dll System.ComponentModel.dll System.Linq.Expressions.dll System.Threading.Tasks.dll Uno.dll System.Numerics.Vectors.dll SkiaSharp.dll System.Buffers.dll SkiaSharp.Views.UWP.dll Uno.UI.Wasm.dll Microsoft.Extensions.Logging.Filter.dll Microsoft.Extensions.Primitives.dll System.Runtime.CompilerServices.Unsafe.dll Microsoft.Extensions.Logging.Console.dll Microsoft.Extensions.Configuration.Abstractions.dll System.Console.dll System.Runtime.InteropServices.RuntimeInformation.dll System.IO.dll Uno.UI.Toolkit.dll > pinvoke-table.h.tmp
4>  [00:00:02.8297824] FAILED: pinvoke-table.h.tmp
4>  [00:00:02.8298490] mono /mnt/c/Users/mattl/AppData/Local/Temp/mono-wasm-05a57bed403/wasm-bcl/wasm_tools/wasm-tuner.exe --gen-pinvoke-table System.Native,libSkiaSharp Uno.Wasm.TimezoneData.dll netstandard.dll mscorlib.dll System.dll Mono.Security.dll System.Xml.dll System.Numerics.dll System.Core.dll WebAssembly.Net.WebSockets.dll WebAssembly.Bindings.dll System.Memory.dll System.Data.dll System.Transactions.dll System.Data.DataSetExtensions.dll System.Drawing.Common.dll System.IO.Compression.dll System.IO.Compression.FileSystem.dll System.ComponentModel.Composition.dll System.Net.Http.dll System.Net.Http.WebAssemblyHttpHandler.dll System.Runtime.Serialization.dll System.ServiceModel.Internals.dll System.Xml.Linq.dll SkiaSharpSample.Wasm.dll Microsoft.Extensions.Logging.Abstractions.dll System.Runtime.dll System.Resources.ResourceManager.dll System.Diagnostics.Debug.dll System.Collections.Concurrent.dll System.Collections.dll System.Globalization.dll System.Linq.dll System.Reflection.dll Uno.UI.dll Uno.Xaml.dll Uno.Foundation.dll Uno.Core.dll System.Collections.Immutable.dll System.Runtime.Extensions.dll System.Threading.dll CommonServiceLocator.dll System.Reflection.Emit.Lightweight.dll System.Reflection.Emit.ILGeneration.dll Microsoft.Extensions.Logging.dll Microsoft.Extensions.DependencyInjection.Abstractions.dll System.ComponentModel.dll System.Linq.Expressions.dll System.Threading.Tasks.dll Uno.dll System.Numerics.Vectors.dll SkiaSharp.dll System.Buffers.dll SkiaSharp.Views.UWP.dll Uno.UI.Wasm.dll Microsoft.Extensions.Logging.Filter.dll Microsoft.Extensions.Primitives.dll System.Runtime.CompilerServices.Unsafe.dll Microsoft.Extensions.Logging.Console.dll Microsoft.Extensions.Configuration.Abstractions.dll System.Console.dll System.Runtime.InteropServices.RuntimeInformation.dll System.IO.dll Uno.UI.Toolkit.dll > pinvoke-table.h.tmp
4>  [00:00:02.8298607] The return type of pinvoke callback method 'System.Void System.Net.NetworkInformation.MacNetworkChange::HandleCallback(System.IntPtr,System.Net.NetworkInformation.MacNetworkChange/NetworkReachabilityFlags,System.IntPtr)' needs to be blittable.
4>  [00:00:08.9775348] [207/212] [EMCC] corebindings.c -> corebindings.o
4>  [00:00:08.9777329] emcc: warning: argument unused during compilation: '-lidbfs.js' [-Wunused-command-line-argument]
4>  [00:00:09.1055952] [208/212] [EMCC] zlib-helper.c -> zlib-helper.o
4>  [00:00:09.1057021] system_libs:INFO: retrieving port: zlib from https://github.com/emscripten-ports/zlib/archive/version_1.zip
4>  [00:00:09.1057049] system_libs:INFO: unpacking port: zlib
4>  [00:00:09.1057066] cache:INFO: generating port: libz.a... (this will be cached in "/home/matthew/.uno/emsdk/emsdk-1.39.18/emsdk/upstream/emscripten/cache/wasm/libz.a" for subsequent builds)
4>  [00:00:09.1057082] cache:INFO:  - ok
4>  [00:00:09.1057098] emcc: warning: argument unused during compilation: '-lidbfs.js' [-Wunused-command-line-argument]
4>  [00:00:09.1063869] ninja: build stopped: subcommand failed.
4>  C:\Users\mattl\.nuget\packages\uno.wasm.bootstrap\1.4.0-pullrequest0249.7\build\Uno.Wasm.Bootstrap.targets(126,2): error : System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
4>  C:\Users\mattl\.nuget\packages\uno.wasm.bootstrap\1.4.0-pullrequest0249.7\build\Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_vbd5d715084dc07047e251108d984271768f25f38.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 657
4>  C:\Users\mattl\.nuget\packages\uno.wasm.bootstrap\1.4.0-pullrequest0249.7\build\Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_vbd5d715084dc07047e251108d984271768f25f38.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 182
4>Done building target "BuildDist" in project "SkiaSharpSample.Wasm.csproj" -- FAILED.
```

**Comment by mattleibow** [comment]
If you need a sample with all the bits and things, the  https://github.com/mono/SkiaSharp/pull/1333 has the bits, just run the WASM project in the Basic/Uno sample.

**Comment by jeromelaban** [comment]
Let's hold to merge this PR until https://github.com/mono/mono/issues/20120 is fixed.

**Comment by mattleibow** [comment]
Just been merged! https://github.com/mono/mono/pull/20121

**Pull request merged**
