### PR TITLE
fix: pass same-origin credentials - fixes #875

### LINKED ISSUE #875: Azure Static Web Apps, with Authentication, WASM fails
### Current behavior

If you deploy to Azure Static Web Apps (a working Uno Platform WASM app)

then turn on basic "Password protection" authentication ("Standard" hosting required)
Screenshot 2024-07-17 at 16 10 17

then reload your app (maybe open an Incognito / Private window, for a fully fresh experience)

you will get the Azure login screen
Screenshot 2024-07-17 at 16 13 28

Enter your password, hit Submit

The page starts to load, but hangs.

Open the Dev Tools (F12) and Refresh the page to see what's going on.

In the console. Lots of errors
Screenshot 2024-07-17 at 16 16 02

and in the Network Tab, you will se that lots of the files in the `package_ ...` folder get issued a 302 redirect back to the authorisation page.
Screenshot 2024-07-17 at 16 19 40

If you request one of these files in a Fresh browser tab, it works
Screenshot 2024-07-17 at 16 22 03
Screenshot 2024-07-17 at 16 22 38

This is because the fresh request can see the Auth cookie.

But the Framed / Embedded request cannot.

Here is the Azure Static Web Apps Cookie - see Application Tab in Developer Tools
Screenshot 2024-07-17 at 16 24 17

This seems like a Browser security issue
see: https://stackoverflow.com/questions/68788202/page-within-iframe-not-seeing-its-own-cookies

--

I have tried various settings in my `staticwebapp.config.json` file to try to alleviate this, namely:
- trying to set some content as `"allowedRoles": "authenticated"`, some as `"allowedRoles": "anonymous"`
- adding various CSP and CORS headers

Screenshot 2024-07-17 at 16 28 06

to no resolution.

--

it would appear, given the browser security settings, this would happen on other web hosting services that are looking for a cookie too.

Any suggestions?

### Expected behavior

a WASM deployed app would work, behind authentication

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

Yes

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

WebAssembly

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by mikeirvingweb**
passing `{credentials: "same-origin"}` into `fetch()` calls made by `Bootstrapper.ts` (`uno-bootstrap.js`in eventual web publish) means that the Uno Platform Wasm App will work on web hosting where we are behind authentication, requiring access to an authentication cookie (such as Azure Static Web Apps 'Password Protection')

addresses, fixes #875

### CODE REVIEW

**Review by carldebilly — COMMENTED** [review]
It would be nice to have a way to test this.

**Comment by mikeirvingweb** [comment]
@carldebilly stick an app in Azure Static Web Apps (paid), turn on Password Protection in Configuration.

Load your App URL, enter your password, if your app loads then the fix works.

Previously the app would fail to load.

**Comment by mikeirvingweb** [comment]
furthermore @carldebilly

to simulate the deployment, without needing the package change live, publish to a folder, then modify `uno-bootstrap.js`

- change `omit` to `same-origin` in `getFetchInit`
- and in `fetchFile`, change the return statement to `return fetch(asset, {credentials: "same-origin"});`

then publish your app using `swa deploy`

**Comment by carldebilly** [comment]
> furthermore @carldebilly
> 
> to simulate the deployment, without needing the package change live, publish to a folder, then modify `uno-bootstrap.js`
> 
> * change `omit` to `same-origin` in `getFetchInit`
> * and in `fetchFile`, change the return statement to `return fetch(asset, {credentials: "same-origin"});`
> 
> then publish your app using `swa deploy`

My comment was more about the ability to create an automated tests in the project CI to test this instead of having to manually test it.

**Comment by jeromelaban** [comment]
Thanks for your contribution! This is likely difficult to validate as-is, but we can definitely try when the dev build will be available. At the very least, the tests passed.

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
