### PR TITLE
fix: Align linker version with ILLinkPack resolution

### PR DESCRIPTION
**Pull request by ebariche**

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]

**Comment by Youssef1313** [comment]
@ebariche @jeromelaban Can we backport to 8.x?

**Comment by Youssef1313** [comment]
This is breaking building net8.0 with .NET 9 SDK.

**Comment by Youssef1313** [comment]
@Mergifyio backport release/stable/8.0

**Comment by jeromelaban** [comment]
https://github.com/Mergifyio backport release/stable/8.0

**Pull request merged**
